// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: delivery/grpc/calendar/proto/calendar.proto

// export PATH="$PATH:$(go env GOPATH)/bin"
// go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
// protoc --go_out=. --go-grpc_out=. --go-grpc_opt=paths=source_relative --go_opt=paths=source_relative delivery/grpc/calendar/proto/calendar.proto

package calendar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CalendarController_GetEventsCalendar_FullMethodName = "/calendar.CalendarController/GetEventsCalendar"
)

// CalendarControllerClient is the client API for CalendarController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalendarControllerClient interface {
	GetEventsCalendar(ctx context.Context, in *GetEventsRequestCalendar, opts ...grpc.CallOption) (*GetEventsResponse, error)
}

type calendarControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarControllerClient(cc grpc.ClientConnInterface) CalendarControllerClient {
	return &calendarControllerClient{cc}
}

func (c *calendarControllerClient) GetEventsCalendar(ctx context.Context, in *GetEventsRequestCalendar, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, CalendarController_GetEventsCalendar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarControllerServer is the server API for CalendarController service.
// All implementations must embed UnimplementedCalendarControllerServer
// for forward compatibility
type CalendarControllerServer interface {
	GetEventsCalendar(context.Context, *GetEventsRequestCalendar) (*GetEventsResponse, error)
	mustEmbedUnimplementedCalendarControllerServer()
}

// UnimplementedCalendarControllerServer must be embedded to have forward compatible implementations.
type UnimplementedCalendarControllerServer struct {
}

func (UnimplementedCalendarControllerServer) GetEventsCalendar(context.Context, *GetEventsRequestCalendar) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventsCalendar not implemented")
}
func (UnimplementedCalendarControllerServer) mustEmbedUnimplementedCalendarControllerServer() {}

// UnsafeCalendarControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalendarControllerServer will
// result in compilation errors.
type UnsafeCalendarControllerServer interface {
	mustEmbedUnimplementedCalendarControllerServer()
}

func RegisterCalendarControllerServer(s grpc.ServiceRegistrar, srv CalendarControllerServer) {
	s.RegisterService(&CalendarController_ServiceDesc, srv)
}

func _CalendarController_GetEventsCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequestCalendar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarControllerServer).GetEventsCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalendarController_GetEventsCalendar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarControllerServer).GetEventsCalendar(ctx, req.(*GetEventsRequestCalendar))
	}
	return interceptor(ctx, in, info, handler)
}

// CalendarController_ServiceDesc is the grpc.ServiceDesc for CalendarController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalendarController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.CalendarController",
	HandlerType: (*CalendarControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventsCalendar",
			Handler:    _CalendarController_GetEventsCalendar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery/grpc/calendar/proto/calendar.proto",
}
